name: pr

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    timeout-minutes: 20

    steps:
      - uses: actions/checkout@v3 # https://github.com/actions/checkout/tags
        with:
          fetch-depth: 0
          ref: master
          clean: true

      - name: Node.js
        uses: actions/setup-node@v3.6.0 # https://github.com/actions/setup-node/tags
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Semantic version
        if: contains(github.event.commits[0].message, '[skip ci]') == false
        run: npm run release -- --dry-run
